### ISSUE TITLE
Standard Properties - Promote the use of shared properties so we can make richer UI for custom types.

### ISSUE THREAD

**Issue by Polleps** [ontola/atomic-server#1005]
We expect users to use the name and description properties in their own classes so we can show them in the UI. But except for the docs we don't actually tell them they should. How do we promote the use of these properties.

## Option 1

Straight up tell them somewhere in the app.
Not very nice UX but easy

## Option 2 

Add them to classes by default. When making a new class in the ontology editor, add them to the list of recommended or required by default. (This makes more sense for name but not really for description.)
It also doesn't really tell the user why they should actually do this.

## Option 3 

Label them as something like 'Standard Properties' in the resource selector UI.
When the user has not typed anything in the searchbox we show a list of resources of that type. We could sort these standard properties to the top and maybe even give them their own category separated with a divider.

**Comment by joepio** [comment]
Something like option 3 seems best IMO.

**Comment by joepio** [comment]
Don't show AtomicData.dev properties, except for a few recommended hardcoded ones (name, description)
