### ISSUE TITLE
Date type (without timestamp) doesn't allow to enter date 

### ISSUE THREAD

**Issue by AlexMikhalev** [ontola/atomic-server#1014]
<img width="674" alt="Screenshot 2024-11-17 at 13 59 04" src="https://github.com/user-attachments/assets/7cfe92cf-de4e-4b1a-a9bb-164e7d82afc5">
If you create a new class with a date type, when you make an instance, it fails the UI check and doesn't allow you to commit because the required property "Release-date" is missing. 
The latest tag from the docker and ontology is public https://common.terraphim.io/drive/h6grD0ID/ontology/learning-rust#list-item-https://common.terraphim.io/drive/h6grD0ID/ontology/learning-rust/class/homepage following astro guide: I wanted to add releases as part of the upcoming article on how to use atomic with vanilla typescript.

**Comment by Polleps** [comment]
You are running an older version. (That markdown input has been replaced a couple of versions ago)
If you did update to a newer version but you still get this old UI it's likely the service worker that needs to refresh. Try clearing all page data by going to the 'application' tab in devtools and clicking the 'clear all data' button. Then reload the page.

**Comment by AlexMikhalev** [comment]
I pulled the latest docker yesterday, so whatever was published in the latest tag was added. 
@joepio do you need to manually push docker into dockerhub?

**Comment by AlexMikhalev** [comment]
Bug is true even in Firefox <img width="1272" alt="Screenshot 2024-11-18 at 11 04 35" src="https://github.com/user-attachments/assets/7cd82d1b-71c5-40ef-a046-284307eb17f5">

**Comment by joepio** [comment]
Problem is that `:latest` tags aren't applied, see #990

You can use `:develop` or `:master`

**Comment by Polleps** [comment]
Looks like this is only a problem with Date inputs, not with Timestamps

**Comment by Polleps** [comment]
Forgot to mention this issue but fixed in https://github.com/atomicdata-dev/atomic-server/commit/121f416c51ed42e81f57937ae1e4e67bfb4389b8
