### ISSUE TITLE
Browser freezes / loop when creating nested resource

### ISSUE THREAD

**Issue by joepio** [ontola/atomic-server#1015]
- Create resource (e.g. class)
- Create nested resource in edit form (e.g. property)
- On save, screen freezes

@AlexMikhalev  and @turkhale

demo: https://vimeo.com/1030305392/21dbbf3904?share=copy

(haven't replicated it myself, but both Alex T and Alex M have had this)

**Comment by Polleps** [comment]
@AlexMikhalev  @turkhale This was a bug in an older version (the inert attribute on body would sometimes not get removed when closing a dialog). It was fixed in version 0.39 or 0.38 (can't remember which one)
