### ISSUE TITLE
Remove openssl dependency - use Rustls for acme / letsencrypt

### ISSUE THREAD

**Issue by joepio** [ontola/atomic-server#192]
I think (although I'm not _entirely_ sure) that OpenSSL is the only runtime dependency of `atomic-server`. It's required only for the HTTPS setup process, which is currently done using `acme_lib`. 

I've had some issues with openssl as a dependency. It makes compiling harder, and i've had that binaries didn't run because of OpenSSL version mismatches. Not fun.

### Fix current implementation [`acme_lib`](https://github.com/algesten/acme-lib)

acme_lib works fine, but it has a bunch of dependencies on OpenSSL for crypto stuff. This could be fixed, with ring for example. But it's not easy - lots of PEM dependencies, which ring doesnt support ([see issue in acme-lib](https://github.com/algesten/acme-lib/issues/57))

### [`rustls-acme`](https://github.com/FlorianUekermann/rustls-acme)

- easy to understand API
- still maintained

### [async-acme](https://crates.io/crates/async-acme)

- Lots of options (rustls / tokio) that minimize deps issues
- No maintenence in a year
- 

### [acme-micro]()

Uses [openssl](https://github.com/kpcyrd/acme-micro/blob/master/Cargo.toml#L21), so no

### [instant_acme](https://github.com/InstantDomain/instant-acme) (my favorite atm)

- Uses rustls and ring (which I use, too)
- Actively maintained
- No HTTP01 support as of now, but [is being worked on](https://github.com/InstantDomain/instant-acme/issues/13)

### (current implementation)

I made the `https` and `https_init` optional features. Not a real solution! 

### Custom implementation

[Poem has a custom implementation](https://github.com/poem-web/poem/tree/e088702121521c8dc8d91d8b35da179ab9922449/poem/src/listener/acme)

[future-io-utils](https://github.com/infinyon/future-aio/blob/master/Cargo.toml#LL24-L30C2) also

- [x] Make HTTPS optional, allows for non-OpenSSL required builds
- [x] Use Rustls for initialization (rustls-acme / async-acme)

**Comment by jonassmedegaard** [comment]
`rustls-acme` uses async-std which is currently used very little (see #366).  Maybe a better option is [async-acme](https://crates.io/crates/async-acme)?

**Comment by jonassmedegaard** [comment]
`rustls-acme` also causes duplicate older branches of `ureq`and `rustls` to be pulled in, because it depends on unstable 0.x APIs and haven't been updated for some time.

**Comment by joepio** [comment]
[async-acme](https://crates.io/crates/async-acme) looks even better indeed!

**Comment by jonassmedegaard** [comment]
until this issue is solved, it might make sense to consider [acme-micro](https://crates.io/crates/acme-micro) which seems a (somewhat) more actively maintained fork of `acme_lib`.

**Comment by joepio** [comment]
This issue just got a bit more important. My own CI pipeline broke because of openssl version mismatch. I didn't know that could happen. It even makes running the docker container impossible.
